name: CoordDump
version: 1.1
author: Kamran
main: com.kamran.coorddump.CoordDump
api-version: 1.17
commands:
  coorddump:
    description: Get information about the player's f stats
    aliases: c
    usage: 'Usage: /coorddump [n|nether|o|overworld|d|discord]'
